const languages = {
    "esp":{
        "start":"INICIO, Ostia",
        "latest":"LO ÚLTIMO, Jolines",
        "reels":"REELS, concha tu mare",
        "contact":"CONTÁCTANOS, cojones",
        "editing1":"EDICIÓN",
        "editing2":"ONLYNE Y OFFLINE",
        "colorCorrection1":"CORRECCIÓN",
        "colorCorrection2":"DE COLOR",
        "motionGraphics1":"MOTION",
        "motionGraphics2":"GRAPHICS",
        "3DAnimation1":"ANIMACIÓN",
        "3DAnimation2":"3D",
        "vfx1":"VFX",
        "vfx2":"",
        "name":"Nombre",
        "email":"E-mail",
        "phone":"Teléfono",
        "message":"Mensaje",
        "sendEmail":"ENVIAR CORREO"
        
    },
    "eng":{
        "start":"START",
        "latest":"LATEST",
        "reels":"REELS",
        "contact":"CONTACT US",
        "editing1":"ONLINE AND OFFLINE",
        "editing2":"EDITING",
        "colorCorrection1":"COLOR",
        "colorCorrection2":"CORRECTION",
        "motionGraphics1":"MOTION",
        "motionGraphics2":"GRAPHICS",
        "3DAnimation1":"3D",
        "3DAnimation2":"ANIMATION",
        "vfx1":"VFX",
        "vfx2":"",
        "name":"Name",
        "email":"E-mail",
        "phone":"Phone",
        "message":"Message",
        "sendEmail":"SEND EMAIL"
    }
};